FROM mcr.microsoft.com/dotnet/core/sdk:3.1.101-buster AS build
WORKDIR /src
COPY *.csproj .
RUN dotnet restore "BlazorWasmSampleModule.csproj"
COPY . .
#RUN dotnet build "BlazorWasmSampleModule.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BlazorWasmSampleModule.csproj" -c Release -o /app/publish

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/BlazorWasmSampleModule/dist .
COPY nginx.conf /etc/nginx/nginx.conf
